DROP DATABASE IF EXISTS Juego;
CREATE DATABASE Juego;
USE Juego;
CREATE TABLE JUGADOR (
 nombre TEXT NOT NULL, // NOT NULL -> no puede contener valores nulos
 pwd VARCHAR(10) NOT NULL, // VARCHAR -> cadena de caracteres
 id INT AUTO_INCREMENT, // AUTO_INCREMENT -> permite generar un n￺mero ￺nico cuando insertamos un nuevo registro en la tabla
 id INTEGER PRIMARY KEY NOT NULL, // INTEGER PRIMARY KEY NOT NULL -> identifica de manera ￺nica cada fila de una tabla
 )ENGINE = InnoDB;

CREATE TABLE PARTIDA (
 ganador INTEGER,
 duracion FLOAT,
 data_temps DATETIME,
 ganador VARCHAR(30),
 id INTEGER PRIMARY KEY NOT NULL,
 )ENGINE = InnoDB;

CREATE TABLE PARTICIPACION (
 JUGADOR INTEGER NOT NULL,
 PARTIDA INTEGER NOT NULL,
 FOREIGN KEY (JUGADOR) REFERENCES JUGADOR(id), // FOREIGN KEY -> columna/as que sirven para se￱alar cual es la clave primaria de otra tabla
 FOREIGN KEY (PARTIDA) REFERENCES PARTIDA(id)
 )ENGINE = InnoDB;


INSERT INTO JUGADOR (nombre, pwd, id) VALUES ('admin', 'admin', 1);
INSERT INTO JUGADOR (nombre, pwd) VALUES ('Alex', '5382');
INSERT INTO JUGADOR (nombre, pwd) VALUES ('Taha', '2904');
INSERT INTO JUGADOR (nombre, pwd) VALUES ('Anna', '2127');

INSERT INTO PARTIDA VALUES (1, '02.10.2022','09:40', 2, 'Taha');
INSERT INTO PARTIDA VALUES (2, '02.10.2022','12:15', 1, 'Anna');
INSERT INTO PARTIDA VALUES (3, '02.10.2022','13:30', 5, 'Taha');
INSERT INTO PARTIDA VALUES (4, '02.10.2022','16:50', 4, 'Alex');
INSERT INTO PARTIDA VALUES (5, '02.10.2022','18:45', 8, 'Alex');
INSERT INTO PARTIDA VALUES (6, '02.10.2022','21:30', 2, 'Anna');

INSERT INTO PARTICIPATION VALUES (1,1);
INSERT INTO PARTICIPATION VALUES (1,2);
INSERT INTO PARTICIPATION VALUES (1,4);
INSERT INTO PARTICIPATION VALUES (2,1);
INSERT INTO PARTICIPATION VALUES (2,2);
INSERT INTO PARTICIPATION VALUES (2,3);
INSERT INTO PARTICIPATION VALUES (3,1);
INSERT INTO PARTICIPATION VALUES (3,3);
INSERT INTO PARTICIPATION VALUES (3,4);
INSERT INTO PARTICIPATION VALUES (4,1);
INSERT INTO PARTICIPATION VALUES (4,2);
INSERT INTO PARTICIPATION VALUES (4,3);
INSERT INTO PARTICIPATION VALUES (4,4);

SELECT COUNT(DISTINCT PARTIDA.id) FROM PARTIDA WHERE PARTIDA.dur > (SELECT MAX(PARTIDA.duracion) FROM PARTIDA;